# Generated by Django 4.2.3 on 2023-07-21 05:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0006_alter_company_company_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('available', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('1', 'Good'), ('2', 'Average'), ('3', 'Bad')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_company', to='Company.company')),
            ],
        ),
    ]
