# Generated by Django 4.2.3 on 2023-07-21 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0002_alter_device_updated_at_devicelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicelog',
            old_name='chekin_date',
            new_name='checkin_date',
        ),
    ]
