# Generated by Django 4.2.3 on 2023-07-20 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0005_alter_company_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
