# Generated by Django 4.2.3 on 2023-07-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_alter_company_company_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
